### ISSUE TITLE
setup help

### ISSUE THREAD

**Issue by edsnowden217** [AjanShrestha/intelius#6]
hey can someone please help me set this up??

**Comment by AjanShrestha** [comment]
Hey mate,

Thank you for the interest in Intelius scraping. I have updated the Readme.

Basically,

## Installation

1. Install node. I think I used node 10 at the time of developing it.
2. Install the npm packages.
```bash
npm install
```

## Run

1. Add email and password of intellius login in .env file in root path.
```bash
email=""
password=""
```
2. npm run start


P.S. : If the website has been updated, the the scraping would not work. Also, keep in mind Intelius has anti-scraping mechanism. The code doesn't have a work around for it.
